wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715238897.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.11.8
      5: 0.16.6
      6: 4.37.2
      8:
      - 1
      - 5
      13: linux-x86_64
